<?xml version = '1.0' encoding = 'ISO-8859-1' ?>
<asm version="1.0" name="0">
	<cp>
		<constant value="EModelCopyGenerator"/>
		<constant value="main"/>
		<constant value="A"/>
		<constant value="EReference"/>
		<constant value="ECORE"/>
		<constant value="assignable"/>
		<constant value="__initassignable"/>
		<constant value="J.registerHelperAttribute(SS):V"/>
		<constant value="EAttribute"/>
		<constant value="ENamedElement"/>
		<constant value="qName"/>
		<constant value="__initqName"/>
		<constant value="EClassifier"/>
		<constant value="EPackage"/>
		<constant value="cname"/>
		<constant value="__initcname"/>
		<constant value="rulename"/>
		<constant value="__initrulename"/>
		<constant value="EClass"/>
		<constant value="hasConcreteSubclasses"/>
		<constant value="__inithasConcreteSubclasses"/>
		<constant value="String"/>
		<constant value="#native"/>
		<constant value="isKeyword"/>
		<constant value="__initisKeyword"/>
		<constant value="-- @atlcompiler atl2006&#10;"/>
		<constant value="-- Generated by: $Id$&#10;"/>
		<constant value="J.+(J):J"/>
		<constant value="module EModelCopy;&#10;&#10;"/>
		<constant value="create OUT : OUTMODEL from IN : INMODEL;&#10;&#10;"/>
		<constant value="helper def : inElements : Set(INMODEL!&quot;ecore::EObject&quot;) = INMODEL!&quot;ecore::EObject&quot;.allInstancesFrom('IN');&#10;&#10;"/>
		<constant value="1"/>
		<constant value="IN"/>
		<constant value="J.allInstancesFrom(J):J"/>
		<constant value="2"/>
		<constant value="J.toRuleString():J"/>
		<constant value="EModelCopy.atl"/>
		<constant value="path"/>
		<constant value="J.writeTo(J):J"/>
		<constant value="15:16-15:32"/>
		<constant value="19:16-19:32"/>
		<constant value="22:16-22:35"/>
		<constant value="25:16-25:33"/>
		<constant value="32:16-32:30"/>
		<constant value="39:16-39:35"/>
		<constant value="50:16-50:35"/>
		<constant value="82:16-82:28"/>
		<constant value="111:16-111:22"/>
		<constant value="5:2-5:29"/>
		<constant value="6:2-6:27"/>
		<constant value="5:2-6:27"/>
		<constant value="7:2-7:26"/>
		<constant value="5:2-7:26"/>
		<constant value="8:2-8:48"/>
		<constant value="5:2-8:48"/>
		<constant value="9:2-9:116"/>
		<constant value="5:2-9:116"/>
		<constant value="4:29-4:41"/>
		<constant value="4:59-4:63"/>
		<constant value="4:29-4:64"/>
		<constant value="10:2-10:5"/>
		<constant value="10:8-10:9"/>
		<constant value="10:8-10:24"/>
		<constant value="10:2-10:24"/>
		<constant value="4:29-10:25"/>
		<constant value="11:10-11:26"/>
		<constant value="11:10-11:31"/>
		<constant value="4:29-11:32"/>
		<constant value="e"/>
		<constant value="acc"/>
		<constant value="self"/>
		<constant value="MECORE!EReference;"/>
		<constant value="0"/>
		<constant value="derived"/>
		<constant value="container"/>
		<constant value="J.or(J):J"/>
		<constant value="J.not():J"/>
		<constant value="changeable"/>
		<constant value="J.and(J):J"/>
		<constant value="16:7-16:11"/>
		<constant value="16:7-16:21"/>
		<constant value="16:25-16:29"/>
		<constant value="16:25-16:39"/>
		<constant value="16:7-16:39"/>
		<constant value="16:2-16:40"/>
		<constant value="17:6-17:10"/>
		<constant value="17:6-17:21"/>
		<constant value="16:2-17:21"/>
		<constant value="MECORE!EAttribute;"/>
		<constant value="20:7-20:11"/>
		<constant value="20:7-20:21"/>
		<constant value="20:2-20:22"/>
		<constant value="20:27-20:31"/>
		<constant value="20:27-20:42"/>
		<constant value="20:2-20:42"/>
		<constant value="MECORE!ENamedElement;"/>
		<constant value="name"/>
		<constant value="23:2-23:6"/>
		<constant value="23:2-23:11"/>
		<constant value="MECORE!EClassifier;"/>
		<constant value="ePackage"/>
		<constant value="J.oclIsUndefined():J"/>
		<constant value="13"/>
		<constant value="::"/>
		<constant value="15"/>
		<constant value="26:5-26:9"/>
		<constant value="26:5-26:18"/>
		<constant value="26:5-26:35"/>
		<constant value="29:3-29:7"/>
		<constant value="29:3-29:16"/>
		<constant value="29:3-29:22"/>
		<constant value="29:25-29:29"/>
		<constant value="29:3-29:29"/>
		<constant value="29:32-29:36"/>
		<constant value="29:32-29:41"/>
		<constant value="29:3-29:41"/>
		<constant value="27:3-27:7"/>
		<constant value="27:3-27:12"/>
		<constant value="26:2-30:7"/>
		<constant value="MECORE!EPackage;"/>
		<constant value="eSuperPackage"/>
		<constant value="33:5-33:9"/>
		<constant value="33:5-33:23"/>
		<constant value="33:5-33:40"/>
		<constant value="36:3-36:7"/>
		<constant value="36:3-36:21"/>
		<constant value="36:3-36:27"/>
		<constant value="36:30-36:34"/>
		<constant value="36:3-36:34"/>
		<constant value="36:37-36:41"/>
		<constant value="36:37-36:46"/>
		<constant value="36:3-36:46"/>
		<constant value="34:3-34:7"/>
		<constant value="34:3-34:12"/>
		<constant value="33:2-37:7"/>
		<constant value="useQualifiedName"/>
		<constant value="17"/>
		<constant value="10"/>
		<constant value="16"/>
		<constant value="&quot;"/>
		<constant value="23"/>
		<constant value="40:5-40:9"/>
		<constant value="40:5-40:26"/>
		<constant value="43:6-43:10"/>
		<constant value="43:6-43:15"/>
		<constant value="43:6-43:25"/>
		<constant value="46:4-46:8"/>
		<constant value="46:4-46:13"/>
		<constant value="44:4-44:7"/>
		<constant value="44:10-44:14"/>
		<constant value="44:10-44:19"/>
		<constant value="44:4-44:19"/>
		<constant value="44:22-44:25"/>
		<constant value="44:4-44:25"/>
		<constant value="43:3-47:8"/>
		<constant value="41:3-41:6"/>
		<constant value="41:9-41:13"/>
		<constant value="41:9-41:19"/>
		<constant value="41:3-41:19"/>
		<constant value="41:22-41:25"/>
		<constant value="41:3-41:25"/>
		<constant value="40:2-48:7"/>
		<constant value="useQualifiedRuleName"/>
		<constant value="51:5-51:9"/>
		<constant value="51:5-51:30"/>
		<constant value="54:6-54:10"/>
		<constant value="54:6-54:15"/>
		<constant value="54:6-54:25"/>
		<constant value="57:4-57:8"/>
		<constant value="57:4-57:13"/>
		<constant value="55:4-55:7"/>
		<constant value="55:10-55:14"/>
		<constant value="55:10-55:19"/>
		<constant value="55:4-55:19"/>
		<constant value="55:22-55:25"/>
		<constant value="55:4-55:25"/>
		<constant value="54:3-58:8"/>
		<constant value="52:3-52:6"/>
		<constant value="52:9-52:13"/>
		<constant value="52:9-52:19"/>
		<constant value="52:3-52:19"/>
		<constant value="52:22-52:25"/>
		<constant value="52:3-52:25"/>
		<constant value="51:2-59:7"/>
		<constant value="toRuleString"/>
		<constant value="MECORE!EClass;"/>
		<constant value="abstract"/>
		<constant value="inclusionCondition"/>
		<constant value="9"/>
		<constant value=""/>
		<constant value="39"/>
		<constant value="rule "/>
		<constant value=" {&#10;"/>
		<constant value="    from s : INMODEL!"/>
		<constant value="J.inputConstraint():J"/>
		<constant value="&#10;"/>
		<constant value="    to t : OUTMODEL!"/>
		<constant value=" ("/>
		<constant value="J.contentsToString():J"/>
		<constant value=")&#10;"/>
		<constant value="}&#10;&#10;"/>
		<constant value="62:9-62:13"/>
		<constant value="62:9-62:24"/>
		<constant value="62:5-62:24"/>
		<constant value="62:29-62:33"/>
		<constant value="62:29-62:52"/>
		<constant value="62:5-62:52"/>
		<constant value="69:3-69:5"/>
		<constant value="63:3-63:10"/>
		<constant value="63:13-63:17"/>
		<constant value="63:13-63:26"/>
		<constant value="63:3-63:26"/>
		<constant value="63:29-63:35"/>
		<constant value="63:3-63:35"/>
		<constant value="64:3-64:26"/>
		<constant value="63:3-64:26"/>
		<constant value="64:29-64:33"/>
		<constant value="64:29-64:39"/>
		<constant value="63:3-64:39"/>
		<constant value="64:42-64:46"/>
		<constant value="64:42-64:64"/>
		<constant value="63:3-64:64"/>
		<constant value="64:67-64:71"/>
		<constant value="63:3-64:71"/>
		<constant value="65:3-65:25"/>
		<constant value="63:3-65:25"/>
		<constant value="65:28-65:32"/>
		<constant value="65:28-65:38"/>
		<constant value="63:3-65:38"/>
		<constant value="65:41-65:45"/>
		<constant value="63:3-65:45"/>
		<constant value="66:3-66:7"/>
		<constant value="66:3-66:26"/>
		<constant value="63:3-66:26"/>
		<constant value="66:29-66:34"/>
		<constant value="63:3-66:34"/>
		<constant value="67:3-67:10"/>
		<constant value="63:3-67:10"/>
		<constant value="62:2-70:7"/>
		<constant value="inputConstraint"/>
		<constant value="5"/>
		<constant value=" (thisModule.inElements-&gt;includes(s))"/>
		<constant value=" (&#10;"/>
		<constant value="&#9;&#9;if thisModule.inElements-&gt;includes(s) then&#10;"/>
		<constant value="&#9;&#9;&#9;s.oclIsTypeOf(INMODEL!"/>
		<constant value="&#9;&#9;else false endif)"/>
		<constant value="73:5-73:9"/>
		<constant value="73:5-73:31"/>
		<constant value="79:3-79:42"/>
		<constant value="74:3-74:9"/>
		<constant value="75:3-75:51"/>
		<constant value="74:3-75:51"/>
		<constant value="76:3-76:30"/>
		<constant value="74:3-76:30"/>
		<constant value="76:33-76:37"/>
		<constant value="76:33-76:43"/>
		<constant value="74:3-76:43"/>
		<constant value="76:46-76:51"/>
		<constant value="74:3-76:51"/>
		<constant value="77:3-77:24"/>
		<constant value="74:3-77:24"/>
		<constant value="73:2-80:7"/>
		<constant value="Sequence"/>
		<constant value="J.allInstances():J"/>
		<constant value="eSuperTypes"/>
		<constant value="J.includes(J):J"/>
		<constant value="B.not():B"/>
		<constant value="21"/>
		<constant value="CJ.including(J):CJ"/>
		<constant value="J.isEmpty():J"/>
		<constant value="83:6-83:18"/>
		<constant value="83:6-83:33"/>
		<constant value="84:3-84:4"/>
		<constant value="84:3-84:16"/>
		<constant value="84:27-84:31"/>
		<constant value="84:3-84:32"/>
		<constant value="84:41-84:42"/>
		<constant value="84:41-84:53"/>
		<constant value="84:37-84:53"/>
		<constant value="84:3-84:53"/>
		<constant value="83:6-84:54"/>
		<constant value="83:6-84:65"/>
		<constant value="83:2-84:65"/>
		<constant value="contentsToString"/>
		<constant value="copyXmiID"/>
		<constant value="7"/>
		<constant value="11"/>
		<constant value="__xmiID__"/>
		<constant value="J.toAssignString():J"/>
		<constant value="J.attributesToString(J):J"/>
		<constant value="J.referencesToString(J):J"/>
		<constant value="87:2-87:6"/>
		<constant value="87:26-87:30"/>
		<constant value="88:6-88:10"/>
		<constant value="88:6-88:20"/>
		<constant value="88:67-88:69"/>
		<constant value="88:26-88:30"/>
		<constant value="88:33-88:44"/>
		<constant value="88:33-88:61"/>
		<constant value="88:26-88:61"/>
		<constant value="88:3-88:75"/>
		<constant value="87:26-88:76"/>
		<constant value="87:2-88:77"/>
		<constant value="attributesToString"/>
		<constant value="J"/>
		<constant value="eAllAttributes"/>
		<constant value="J.featuresToString(JJ):J"/>
		<constant value="91:2-91:6"/>
		<constant value="91:24-91:28"/>
		<constant value="91:30-91:34"/>
		<constant value="91:30-91:49"/>
		<constant value="91:60-91:61"/>
		<constant value="91:60-91:72"/>
		<constant value="91:30-91:73"/>
		<constant value="91:2-91:74"/>
		<constant value="a"/>
		<constant value="head"/>
		<constant value="referencesToString"/>
		<constant value="eAllReferences"/>
		<constant value="94:2-94:6"/>
		<constant value="94:24-94:28"/>
		<constant value="94:30-94:34"/>
		<constant value="94:30-94:49"/>
		<constant value="94:60-94:61"/>
		<constant value="94:60-94:72"/>
		<constant value="94:30-94:73"/>
		<constant value="94:2-94:74"/>
		<constant value="r"/>
		<constant value="featuresToString"/>
		<constant value="3"/>
		<constant value="4"/>
		<constant value="J.size():J"/>
		<constant value="J.=(J):J"/>
		<constant value="18"/>
		<constant value=",&#10;"/>
		<constant value="97:37-97:41"/>
		<constant value="97:2-97:9"/>
		<constant value="98:6-98:9"/>
		<constant value="98:6-98:16"/>
		<constant value="98:19-98:20"/>
		<constant value="98:6-98:20"/>
		<constant value="101:4-101:7"/>
		<constant value="101:10-101:15"/>
		<constant value="101:4-101:15"/>
		<constant value="101:18-101:19"/>
		<constant value="101:18-101:24"/>
		<constant value="101:18-101:41"/>
		<constant value="101:4-101:41"/>
		<constant value="99:4-99:8"/>
		<constant value="99:11-99:12"/>
		<constant value="99:11-99:17"/>
		<constant value="99:11-99:34"/>
		<constant value="99:4-99:34"/>
		<constant value="98:3-102:8"/>
		<constant value="97:2-102:9"/>
		<constant value="feature"/>
		<constant value="toAssignString"/>
		<constant value="S"/>
		<constant value="        "/>
		<constant value=" &lt;- s."/>
		<constant value="20"/>
		<constant value="        &quot;"/>
		<constant value="&quot; &lt;- s.&quot;"/>
		<constant value="105:5-105:9"/>
		<constant value="105:5-105:19"/>
		<constant value="108:3-108:13"/>
		<constant value="108:16-108:20"/>
		<constant value="108:3-108:20"/>
		<constant value="108:23-108:31"/>
		<constant value="108:3-108:31"/>
		<constant value="108:34-108:38"/>
		<constant value="108:3-108:38"/>
		<constant value="106:3-106:14"/>
		<constant value="106:17-106:21"/>
		<constant value="106:3-106:21"/>
		<constant value="106:24-106:34"/>
		<constant value="106:3-106:34"/>
		<constant value="106:37-106:41"/>
		<constant value="106:3-106:41"/>
		<constant value="106:44-106:47"/>
		<constant value="106:3-106:47"/>
		<constant value="105:2-109:7"/>
		<constant value="Set"/>
		<constant value="module"/>
		<constant value="create"/>
		<constant value="from"/>
		<constant value="rule"/>
		<constant value="to"/>
		<constant value="using"/>
		<constant value="helper"/>
		<constant value="context"/>
		<constant value="def"/>
		<constant value="and"/>
		<constant value="or"/>
		<constant value="not"/>
		<constant value="if"/>
		<constant value="then"/>
		<constant value="else"/>
		<constant value="endif"/>
		<constant value="query"/>
		<constant value="library"/>
		<constant value="mapsTo"/>
		<constant value="Boolean"/>
		<constant value="Integer"/>
		<constant value="Real"/>
		<constant value="Bag"/>
		<constant value="OrderedSet"/>
		<constant value="refining"/>
		<constant value="foreach"/>
		<constant value="distinct"/>
		<constant value="in"/>
		<constant value="do"/>
		<constant value="uses"/>
		<constant value="let"/>
		<constant value="TupleType"/>
		<constant value="112:6-112:14"/>
		<constant value="112:16-112:24"/>
		<constant value="112:26-112:32"/>
		<constant value="112:34-112:40"/>
		<constant value="112:42-112:46"/>
		<constant value="112:48-112:55"/>
		<constant value="112:57-112:65"/>
		<constant value="112:67-112:76"/>
		<constant value="113:3-113:8"/>
		<constant value="113:10-113:15"/>
		<constant value="113:17-113:21"/>
		<constant value="113:23-113:28"/>
		<constant value="113:30-113:34"/>
		<constant value="113:36-113:42"/>
		<constant value="113:44-113:50"/>
		<constant value="113:52-113:59"/>
		<constant value="113:61-113:68"/>
		<constant value="114:3-114:12"/>
		<constant value="114:14-114:22"/>
		<constant value="114:24-114:32"/>
		<constant value="114:34-114:43"/>
		<constant value="114:45-114:54"/>
		<constant value="114:56-114:62"/>
		<constant value="114:64-114:69"/>
		<constant value="115:3-115:8"/>
		<constant value="115:10-115:22"/>
		<constant value="115:24-115:34"/>
		<constant value="115:36-115:46"/>
		<constant value="115:48-115:57"/>
		<constant value="115:59-115:69"/>
		<constant value="116:3-116:12"/>
		<constant value="116:14-116:24"/>
		<constant value="116:26-116:30"/>
		<constant value="116:32-116:36"/>
		<constant value="116:38-116:44"/>
		<constant value="116:46-116:51"/>
		<constant value="116:53-116:64"/>
		<constant value="112:2-116:65"/>
		<constant value="116:76-116:80"/>
		<constant value="112:2-116:81"/>
	</cp>
	<operation name="1">
		<context type="2"/>
		<parameters>
		</parameters>
		<code>
			<push arg="3"/>
			<push arg="4"/>
			<findme/>
			<push arg="5"/>
			<push arg="6"/>
			<pcall arg="7"/>
			<push arg="8"/>
			<push arg="4"/>
			<findme/>
			<push arg="5"/>
			<push arg="6"/>
			<pcall arg="7"/>
			<push arg="9"/>
			<push arg="4"/>
			<findme/>
			<push arg="10"/>
			<push arg="11"/>
			<pcall arg="7"/>
			<push arg="12"/>
			<push arg="4"/>
			<findme/>
			<push arg="10"/>
			<push arg="11"/>
			<pcall arg="7"/>
			<push arg="13"/>
			<push arg="4"/>
			<findme/>
			<push arg="10"/>
			<push arg="11"/>
			<pcall arg="7"/>
			<push arg="9"/>
			<push arg="4"/>
			<findme/>
			<push arg="14"/>
			<push arg="15"/>
			<pcall arg="7"/>
			<push arg="9"/>
			<push arg="4"/>
			<findme/>
			<push arg="16"/>
			<push arg="17"/>
			<pcall arg="7"/>
			<push arg="18"/>
			<push arg="4"/>
			<findme/>
			<push arg="19"/>
			<push arg="20"/>
			<pcall arg="7"/>
			<push arg="21"/>
			<push arg="22"/>
			<findme/>
			<push arg="23"/>
			<push arg="24"/>
			<pcall arg="7"/>
			<push arg="25"/>
			<push arg="26"/>
			<call arg="27"/>
			<push arg="28"/>
			<call arg="27"/>
			<push arg="29"/>
			<call arg="27"/>
			<push arg="30"/>
			<call arg="27"/>
			<store arg="31"/>
			<push arg="18"/>
			<push arg="4"/>
			<findme/>
			<push arg="32"/>
			<call arg="33"/>
			<iterate/>
			<store arg="34"/>
			<load arg="31"/>
			<load arg="34"/>
			<call arg="35"/>
			<call arg="27"/>
			<store arg="31"/>
			<enditerate/>
			<load arg="31"/>
			<push arg="36"/>
			<get arg="37"/>
			<call arg="38"/>
		</code>
		<linenumbertable>
			<lne id="39" begin="0" end="2"/>
			<lne id="40" begin="6" end="8"/>
			<lne id="41" begin="12" end="14"/>
			<lne id="42" begin="18" end="20"/>
			<lne id="43" begin="24" end="26"/>
			<lne id="44" begin="30" end="32"/>
			<lne id="45" begin="36" end="38"/>
			<lne id="46" begin="42" end="44"/>
			<lne id="47" begin="48" end="50"/>
			<lne id="48" begin="54" end="54"/>
			<lne id="49" begin="55" end="55"/>
			<lne id="50" begin="54" end="56"/>
			<lne id="51" begin="57" end="57"/>
			<lne id="52" begin="54" end="58"/>
			<lne id="53" begin="59" end="59"/>
			<lne id="54" begin="54" end="60"/>
			<lne id="55" begin="61" end="61"/>
			<lne id="56" begin="54" end="62"/>
			<lne id="57" begin="64" end="66"/>
			<lne id="58" begin="67" end="67"/>
			<lne id="59" begin="64" end="68"/>
			<lne id="60" begin="71" end="71"/>
			<lne id="61" begin="72" end="72"/>
			<lne id="62" begin="72" end="73"/>
			<lne id="63" begin="71" end="74"/>
			<lne id="64" begin="54" end="77"/>
			<lne id="65" begin="78" end="78"/>
			<lne id="66" begin="78" end="79"/>
			<lne id="67" begin="54" end="80"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="2" name="68" begin="70" end="75"/>
			<lve slot="1" name="69" begin="63" end="77"/>
			<lve slot="0" name="70" begin="0" end="80"/>
		</localvariabletable>
	</operation>
	<operation name="6">
		<context type="71"/>
		<parameters>
		</parameters>
		<code>
			<load arg="72"/>
			<get arg="73"/>
			<load arg="72"/>
			<get arg="74"/>
			<call arg="75"/>
			<call arg="76"/>
			<load arg="72"/>
			<get arg="77"/>
			<call arg="78"/>
		</code>
		<linenumbertable>
			<lne id="79" begin="0" end="0"/>
			<lne id="80" begin="0" end="1"/>
			<lne id="81" begin="2" end="2"/>
			<lne id="82" begin="2" end="3"/>
			<lne id="83" begin="0" end="4"/>
			<lne id="84" begin="0" end="5"/>
			<lne id="85" begin="6" end="6"/>
			<lne id="86" begin="6" end="7"/>
			<lne id="87" begin="0" end="8"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="0" name="70" begin="0" end="8"/>
		</localvariabletable>
	</operation>
	<operation name="6">
		<context type="88"/>
		<parameters>
		</parameters>
		<code>
			<load arg="72"/>
			<get arg="73"/>
			<call arg="76"/>
			<load arg="72"/>
			<get arg="77"/>
			<call arg="78"/>
		</code>
		<linenumbertable>
			<lne id="89" begin="0" end="0"/>
			<lne id="90" begin="0" end="1"/>
			<lne id="91" begin="0" end="2"/>
			<lne id="92" begin="3" end="3"/>
			<lne id="93" begin="3" end="4"/>
			<lne id="94" begin="0" end="5"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="0" name="70" begin="0" end="5"/>
		</localvariabletable>
	</operation>
	<operation name="11">
		<context type="95"/>
		<parameters>
		</parameters>
		<code>
			<load arg="72"/>
			<get arg="96"/>
		</code>
		<linenumbertable>
			<lne id="97" begin="0" end="0"/>
			<lne id="98" begin="0" end="1"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="0" name="70" begin="0" end="1"/>
		</localvariabletable>
	</operation>
	<operation name="11">
		<context type="99"/>
		<parameters>
		</parameters>
		<code>
			<load arg="72"/>
			<get arg="100"/>
			<call arg="101"/>
			<if arg="102"/>
			<load arg="72"/>
			<get arg="100"/>
			<get arg="10"/>
			<push arg="103"/>
			<call arg="27"/>
			<load arg="72"/>
			<get arg="96"/>
			<call arg="27"/>
			<goto arg="104"/>
			<load arg="72"/>
			<get arg="96"/>
		</code>
		<linenumbertable>
			<lne id="105" begin="0" end="0"/>
			<lne id="106" begin="0" end="1"/>
			<lne id="107" begin="0" end="2"/>
			<lne id="108" begin="4" end="4"/>
			<lne id="109" begin="4" end="5"/>
			<lne id="110" begin="4" end="6"/>
			<lne id="111" begin="7" end="7"/>
			<lne id="112" begin="4" end="8"/>
			<lne id="113" begin="9" end="9"/>
			<lne id="114" begin="9" end="10"/>
			<lne id="115" begin="4" end="11"/>
			<lne id="116" begin="13" end="13"/>
			<lne id="117" begin="13" end="14"/>
			<lne id="118" begin="0" end="14"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="0" name="70" begin="0" end="14"/>
		</localvariabletable>
	</operation>
	<operation name="11">
		<context type="119"/>
		<parameters>
		</parameters>
		<code>
			<load arg="72"/>
			<get arg="120"/>
			<call arg="101"/>
			<if arg="102"/>
			<load arg="72"/>
			<get arg="120"/>
			<get arg="10"/>
			<push arg="103"/>
			<call arg="27"/>
			<load arg="72"/>
			<get arg="96"/>
			<call arg="27"/>
			<goto arg="104"/>
			<load arg="72"/>
			<get arg="96"/>
		</code>
		<linenumbertable>
			<lne id="121" begin="0" end="0"/>
			<lne id="122" begin="0" end="1"/>
			<lne id="123" begin="0" end="2"/>
			<lne id="124" begin="4" end="4"/>
			<lne id="125" begin="4" end="5"/>
			<lne id="126" begin="4" end="6"/>
			<lne id="127" begin="7" end="7"/>
			<lne id="128" begin="4" end="8"/>
			<lne id="129" begin="9" end="9"/>
			<lne id="130" begin="9" end="10"/>
			<lne id="131" begin="4" end="11"/>
			<lne id="132" begin="13" end="13"/>
			<lne id="133" begin="13" end="14"/>
			<lne id="134" begin="0" end="14"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="0" name="70" begin="0" end="14"/>
		</localvariabletable>
	</operation>
	<operation name="15">
		<context type="95"/>
		<parameters>
		</parameters>
		<code>
			<load arg="72"/>
			<get arg="135"/>
			<if arg="136"/>
			<load arg="72"/>
			<get arg="96"/>
			<get arg="23"/>
			<if arg="137"/>
			<load arg="72"/>
			<get arg="96"/>
			<goto arg="138"/>
			<push arg="139"/>
			<load arg="72"/>
			<get arg="96"/>
			<call arg="27"/>
			<push arg="139"/>
			<call arg="27"/>
			<goto arg="140"/>
			<push arg="139"/>
			<load arg="72"/>
			<get arg="10"/>
			<call arg="27"/>
			<push arg="139"/>
			<call arg="27"/>
		</code>
		<linenumbertable>
			<lne id="141" begin="0" end="0"/>
			<lne id="142" begin="0" end="1"/>
			<lne id="143" begin="3" end="3"/>
			<lne id="144" begin="3" end="4"/>
			<lne id="145" begin="3" end="5"/>
			<lne id="146" begin="7" end="7"/>
			<lne id="147" begin="7" end="8"/>
			<lne id="148" begin="10" end="10"/>
			<lne id="149" begin="11" end="11"/>
			<lne id="150" begin="11" end="12"/>
			<lne id="151" begin="10" end="13"/>
			<lne id="152" begin="14" end="14"/>
			<lne id="153" begin="10" end="15"/>
			<lne id="154" begin="3" end="15"/>
			<lne id="155" begin="17" end="17"/>
			<lne id="156" begin="18" end="18"/>
			<lne id="157" begin="18" end="19"/>
			<lne id="158" begin="17" end="20"/>
			<lne id="159" begin="21" end="21"/>
			<lne id="160" begin="17" end="22"/>
			<lne id="161" begin="0" end="22"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="0" name="70" begin="0" end="22"/>
		</localvariabletable>
	</operation>
	<operation name="17">
		<context type="95"/>
		<parameters>
		</parameters>
		<code>
			<load arg="72"/>
			<get arg="162"/>
			<if arg="136"/>
			<load arg="72"/>
			<get arg="96"/>
			<get arg="23"/>
			<if arg="137"/>
			<load arg="72"/>
			<get arg="96"/>
			<goto arg="138"/>
			<push arg="139"/>
			<load arg="72"/>
			<get arg="96"/>
			<call arg="27"/>
			<push arg="139"/>
			<call arg="27"/>
			<goto arg="140"/>
			<push arg="139"/>
			<load arg="72"/>
			<get arg="10"/>
			<call arg="27"/>
			<push arg="139"/>
			<call arg="27"/>
		</code>
		<linenumbertable>
			<lne id="163" begin="0" end="0"/>
			<lne id="164" begin="0" end="1"/>
			<lne id="165" begin="3" end="3"/>
			<lne id="166" begin="3" end="4"/>
			<lne id="167" begin="3" end="5"/>
			<lne id="168" begin="7" end="7"/>
			<lne id="169" begin="7" end="8"/>
			<lne id="170" begin="10" end="10"/>
			<lne id="171" begin="11" end="11"/>
			<lne id="172" begin="11" end="12"/>
			<lne id="173" begin="10" end="13"/>
			<lne id="174" begin="14" end="14"/>
			<lne id="175" begin="10" end="15"/>
			<lne id="176" begin="3" end="15"/>
			<lne id="177" begin="17" end="17"/>
			<lne id="178" begin="18" end="18"/>
			<lne id="179" begin="18" end="19"/>
			<lne id="180" begin="17" end="20"/>
			<lne id="181" begin="21" end="21"/>
			<lne id="182" begin="17" end="22"/>
			<lne id="183" begin="0" end="22"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="0" name="70" begin="0" end="22"/>
		</localvariabletable>
	</operation>
	<operation name="184">
		<context type="185"/>
		<parameters>
		</parameters>
		<code>
			<load arg="72"/>
			<get arg="186"/>
			<call arg="76"/>
			<load arg="72"/>
			<get arg="187"/>
			<call arg="78"/>
			<if arg="188"/>
			<push arg="189"/>
			<goto arg="190"/>
			<push arg="191"/>
			<load arg="72"/>
			<get arg="16"/>
			<call arg="27"/>
			<push arg="192"/>
			<call arg="27"/>
			<push arg="193"/>
			<call arg="27"/>
			<load arg="72"/>
			<get arg="14"/>
			<call arg="27"/>
			<load arg="72"/>
			<call arg="194"/>
			<call arg="27"/>
			<push arg="195"/>
			<call arg="27"/>
			<push arg="196"/>
			<call arg="27"/>
			<load arg="72"/>
			<get arg="14"/>
			<call arg="27"/>
			<push arg="197"/>
			<call arg="27"/>
			<load arg="72"/>
			<call arg="198"/>
			<call arg="27"/>
			<push arg="199"/>
			<call arg="27"/>
			<push arg="200"/>
			<call arg="27"/>
		</code>
		<linenumbertable>
			<lne id="201" begin="0" end="0"/>
			<lne id="202" begin="0" end="1"/>
			<lne id="203" begin="0" end="2"/>
			<lne id="204" begin="3" end="3"/>
			<lne id="205" begin="3" end="4"/>
			<lne id="206" begin="0" end="5"/>
			<lne id="207" begin="7" end="7"/>
			<lne id="208" begin="9" end="9"/>
			<lne id="209" begin="10" end="10"/>
			<lne id="210" begin="10" end="11"/>
			<lne id="211" begin="9" end="12"/>
			<lne id="212" begin="13" end="13"/>
			<lne id="213" begin="9" end="14"/>
			<lne id="214" begin="15" end="15"/>
			<lne id="215" begin="9" end="16"/>
			<lne id="216" begin="17" end="17"/>
			<lne id="217" begin="17" end="18"/>
			<lne id="218" begin="9" end="19"/>
			<lne id="219" begin="20" end="20"/>
			<lne id="220" begin="20" end="21"/>
			<lne id="221" begin="9" end="22"/>
			<lne id="222" begin="23" end="23"/>
			<lne id="223" begin="9" end="24"/>
			<lne id="224" begin="25" end="25"/>
			<lne id="225" begin="9" end="26"/>
			<lne id="226" begin="27" end="27"/>
			<lne id="227" begin="27" end="28"/>
			<lne id="228" begin="9" end="29"/>
			<lne id="229" begin="30" end="30"/>
			<lne id="230" begin="9" end="31"/>
			<lne id="231" begin="32" end="32"/>
			<lne id="232" begin="32" end="33"/>
			<lne id="233" begin="9" end="34"/>
			<lne id="234" begin="35" end="35"/>
			<lne id="235" begin="9" end="36"/>
			<lne id="236" begin="37" end="37"/>
			<lne id="237" begin="9" end="38"/>
			<lne id="238" begin="0" end="38"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="0" name="70" begin="0" end="38"/>
		</localvariabletable>
	</operation>
	<operation name="239">
		<context type="185"/>
		<parameters>
		</parameters>
		<code>
			<load arg="72"/>
			<get arg="19"/>
			<if arg="240"/>
			<push arg="241"/>
			<goto arg="136"/>
			<push arg="242"/>
			<push arg="243"/>
			<call arg="27"/>
			<push arg="244"/>
			<call arg="27"/>
			<load arg="72"/>
			<get arg="14"/>
			<call arg="27"/>
			<push arg="199"/>
			<call arg="27"/>
			<push arg="245"/>
			<call arg="27"/>
		</code>
		<linenumbertable>
			<lne id="246" begin="0" end="0"/>
			<lne id="247" begin="0" end="1"/>
			<lne id="248" begin="3" end="3"/>
			<lne id="249" begin="5" end="5"/>
			<lne id="250" begin="6" end="6"/>
			<lne id="251" begin="5" end="7"/>
			<lne id="252" begin="8" end="8"/>
			<lne id="253" begin="5" end="9"/>
			<lne id="254" begin="10" end="10"/>
			<lne id="255" begin="10" end="11"/>
			<lne id="256" begin="5" end="12"/>
			<lne id="257" begin="13" end="13"/>
			<lne id="258" begin="5" end="14"/>
			<lne id="259" begin="15" end="15"/>
			<lne id="260" begin="5" end="16"/>
			<lne id="261" begin="0" end="16"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="0" name="70" begin="0" end="16"/>
		</localvariabletable>
	</operation>
	<operation name="20">
		<context type="185"/>
		<parameters>
		</parameters>
		<code>
			<push arg="262"/>
			<push arg="22"/>
			<new/>
			<push arg="18"/>
			<push arg="4"/>
			<findme/>
			<call arg="263"/>
			<iterate/>
			<store arg="31"/>
			<load arg="31"/>
			<get arg="264"/>
			<load arg="72"/>
			<call arg="265"/>
			<load arg="31"/>
			<get arg="186"/>
			<call arg="76"/>
			<call arg="78"/>
			<call arg="266"/>
			<if arg="267"/>
			<load arg="31"/>
			<call arg="268"/>
			<enditerate/>
			<call arg="269"/>
			<call arg="76"/>
		</code>
		<linenumbertable>
			<lne id="270" begin="3" end="5"/>
			<lne id="271" begin="3" end="6"/>
			<lne id="272" begin="9" end="9"/>
			<lne id="273" begin="9" end="10"/>
			<lne id="274" begin="11" end="11"/>
			<lne id="275" begin="9" end="12"/>
			<lne id="276" begin="13" end="13"/>
			<lne id="277" begin="13" end="14"/>
			<lne id="278" begin="13" end="15"/>
			<lne id="279" begin="9" end="16"/>
			<lne id="280" begin="0" end="21"/>
			<lne id="281" begin="0" end="22"/>
			<lne id="282" begin="0" end="23"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="1" name="68" begin="8" end="20"/>
			<lve slot="0" name="70" begin="0" end="23"/>
		</localvariabletable>
	</operation>
	<operation name="283">
		<context type="185"/>
		<parameters>
		</parameters>
		<code>
			<load arg="72"/>
			<load arg="72"/>
			<load arg="72"/>
			<get arg="284"/>
			<if arg="285"/>
			<push arg="189"/>
			<goto arg="286"/>
			<push arg="195"/>
			<push arg="287"/>
			<call arg="288"/>
			<call arg="27"/>
			<call arg="289"/>
			<call arg="290"/>
		</code>
		<linenumbertable>
			<lne id="291" begin="0" end="0"/>
			<lne id="292" begin="1" end="1"/>
			<lne id="293" begin="2" end="2"/>
			<lne id="294" begin="2" end="3"/>
			<lne id="295" begin="5" end="5"/>
			<lne id="296" begin="7" end="7"/>
			<lne id="297" begin="8" end="8"/>
			<lne id="298" begin="8" end="9"/>
			<lne id="299" begin="7" end="10"/>
			<lne id="300" begin="2" end="10"/>
			<lne id="301" begin="1" end="11"/>
			<lne id="302" begin="0" end="12"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="0" name="70" begin="0" end="12"/>
		</localvariabletable>
	</operation>
	<operation name="303">
		<context type="185"/>
		<parameters>
			<parameter name="31" type="304"/>
		</parameters>
		<code>
			<load arg="72"/>
			<load arg="31"/>
			<push arg="262"/>
			<push arg="22"/>
			<new/>
			<load arg="72"/>
			<get arg="305"/>
			<iterate/>
			<store arg="34"/>
			<load arg="34"/>
			<get arg="5"/>
			<call arg="266"/>
			<if arg="104"/>
			<load arg="34"/>
			<call arg="268"/>
			<enditerate/>
			<call arg="306"/>
		</code>
		<linenumbertable>
			<lne id="307" begin="0" end="0"/>
			<lne id="308" begin="1" end="1"/>
			<lne id="309" begin="5" end="5"/>
			<lne id="310" begin="5" end="6"/>
			<lne id="311" begin="9" end="9"/>
			<lne id="312" begin="9" end="10"/>
			<lne id="313" begin="2" end="15"/>
			<lne id="314" begin="0" end="16"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="2" name="315" begin="8" end="14"/>
			<lve slot="0" name="70" begin="0" end="16"/>
			<lve slot="1" name="316" begin="0" end="16"/>
		</localvariabletable>
	</operation>
	<operation name="317">
		<context type="185"/>
		<parameters>
			<parameter name="31" type="304"/>
		</parameters>
		<code>
			<load arg="72"/>
			<load arg="31"/>
			<push arg="262"/>
			<push arg="22"/>
			<new/>
			<load arg="72"/>
			<get arg="318"/>
			<iterate/>
			<store arg="34"/>
			<load arg="34"/>
			<get arg="5"/>
			<call arg="266"/>
			<if arg="104"/>
			<load arg="34"/>
			<call arg="268"/>
			<enditerate/>
			<call arg="306"/>
		</code>
		<linenumbertable>
			<lne id="319" begin="0" end="0"/>
			<lne id="320" begin="1" end="1"/>
			<lne id="321" begin="5" end="5"/>
			<lne id="322" begin="5" end="6"/>
			<lne id="323" begin="9" end="9"/>
			<lne id="324" begin="9" end="10"/>
			<lne id="325" begin="2" end="15"/>
			<lne id="326" begin="0" end="16"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="2" name="327" begin="8" end="14"/>
			<lve slot="0" name="70" begin="0" end="16"/>
			<lve slot="1" name="316" begin="0" end="16"/>
		</localvariabletable>
	</operation>
	<operation name="328">
		<context type="185"/>
		<parameters>
			<parameter name="31" type="304"/>
			<parameter name="34" type="304"/>
		</parameters>
		<code>
			<load arg="31"/>
			<store arg="329"/>
			<load arg="34"/>
			<iterate/>
			<store arg="330"/>
			<load arg="329"/>
			<call arg="331"/>
			<pushi arg="72"/>
			<call arg="332"/>
			<if arg="333"/>
			<load arg="329"/>
			<push arg="334"/>
			<call arg="27"/>
			<load arg="330"/>
			<get arg="96"/>
			<call arg="288"/>
			<call arg="27"/>
			<goto arg="140"/>
			<push arg="195"/>
			<load arg="330"/>
			<get arg="96"/>
			<call arg="288"/>
			<call arg="27"/>
			<store arg="329"/>
			<enditerate/>
			<load arg="329"/>
		</code>
		<linenumbertable>
			<lne id="335" begin="0" end="0"/>
			<lne id="336" begin="2" end="2"/>
			<lne id="337" begin="5" end="5"/>
			<lne id="338" begin="5" end="6"/>
			<lne id="339" begin="7" end="7"/>
			<lne id="340" begin="5" end="8"/>
			<lne id="341" begin="10" end="10"/>
			<lne id="342" begin="11" end="11"/>
			<lne id="343" begin="10" end="12"/>
			<lne id="344" begin="13" end="13"/>
			<lne id="345" begin="13" end="14"/>
			<lne id="346" begin="13" end="15"/>
			<lne id="347" begin="10" end="16"/>
			<lne id="348" begin="18" end="18"/>
			<lne id="349" begin="19" end="19"/>
			<lne id="350" begin="19" end="20"/>
			<lne id="351" begin="19" end="21"/>
			<lne id="352" begin="18" end="22"/>
			<lne id="353" begin="5" end="22"/>
			<lne id="354" begin="0" end="25"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="4" name="68" begin="4" end="23"/>
			<lve slot="3" name="69" begin="1" end="25"/>
			<lve slot="0" name="70" begin="0" end="25"/>
			<lve slot="1" name="316" begin="0" end="25"/>
			<lve slot="2" name="355" begin="0" end="25"/>
		</localvariabletable>
	</operation>
	<operation name="356">
		<context type="357"/>
		<parameters>
		</parameters>
		<code>
			<load arg="72"/>
			<get arg="23"/>
			<if arg="286"/>
			<push arg="358"/>
			<load arg="72"/>
			<call arg="27"/>
			<push arg="359"/>
			<call arg="27"/>
			<load arg="72"/>
			<call arg="27"/>
			<goto arg="360"/>
			<push arg="361"/>
			<load arg="72"/>
			<call arg="27"/>
			<push arg="362"/>
			<call arg="27"/>
			<load arg="72"/>
			<call arg="27"/>
			<push arg="139"/>
			<call arg="27"/>
		</code>
		<linenumbertable>
			<lne id="363" begin="0" end="0"/>
			<lne id="364" begin="0" end="1"/>
			<lne id="365" begin="3" end="3"/>
			<lne id="366" begin="4" end="4"/>
			<lne id="367" begin="3" end="5"/>
			<lne id="368" begin="6" end="6"/>
			<lne id="369" begin="3" end="7"/>
			<lne id="370" begin="8" end="8"/>
			<lne id="371" begin="3" end="9"/>
			<lne id="372" begin="11" end="11"/>
			<lne id="373" begin="12" end="12"/>
			<lne id="374" begin="11" end="13"/>
			<lne id="375" begin="14" end="14"/>
			<lne id="376" begin="11" end="15"/>
			<lne id="377" begin="16" end="16"/>
			<lne id="378" begin="11" end="17"/>
			<lne id="379" begin="18" end="18"/>
			<lne id="380" begin="11" end="19"/>
			<lne id="381" begin="0" end="19"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="0" name="70" begin="0" end="19"/>
		</localvariabletable>
	</operation>
	<operation name="24">
		<context type="357"/>
		<parameters>
		</parameters>
		<code>
			<push arg="382"/>
			<push arg="22"/>
			<new/>
			<push arg="383"/>
			<call arg="268"/>
			<push arg="384"/>
			<call arg="268"/>
			<push arg="385"/>
			<call arg="268"/>
			<push arg="386"/>
			<call arg="268"/>
			<push arg="387"/>
			<call arg="268"/>
			<push arg="388"/>
			<call arg="268"/>
			<push arg="389"/>
			<call arg="268"/>
			<push arg="390"/>
			<call arg="268"/>
			<push arg="391"/>
			<call arg="268"/>
			<push arg="392"/>
			<call arg="268"/>
			<push arg="393"/>
			<call arg="268"/>
			<push arg="394"/>
			<call arg="268"/>
			<push arg="395"/>
			<call arg="268"/>
			<push arg="396"/>
			<call arg="268"/>
			<push arg="397"/>
			<call arg="268"/>
			<push arg="398"/>
			<call arg="268"/>
			<push arg="399"/>
			<call arg="268"/>
			<push arg="400"/>
			<call arg="268"/>
			<push arg="401"/>
			<call arg="268"/>
			<push arg="21"/>
			<call arg="268"/>
			<push arg="402"/>
			<call arg="268"/>
			<push arg="403"/>
			<call arg="268"/>
			<push arg="404"/>
			<call arg="268"/>
			<push arg="405"/>
			<call arg="268"/>
			<push arg="382"/>
			<call arg="268"/>
			<push arg="406"/>
			<call arg="268"/>
			<push arg="262"/>
			<call arg="268"/>
			<push arg="186"/>
			<call arg="268"/>
			<push arg="73"/>
			<call arg="268"/>
			<push arg="407"/>
			<call arg="268"/>
			<push arg="408"/>
			<call arg="268"/>
			<push arg="409"/>
			<call arg="268"/>
			<push arg="410"/>
			<call arg="268"/>
			<push arg="411"/>
			<call arg="268"/>
			<push arg="412"/>
			<call arg="268"/>
			<push arg="413"/>
			<call arg="268"/>
			<push arg="414"/>
			<call arg="268"/>
			<load arg="72"/>
			<call arg="265"/>
		</code>
		<linenumbertable>
			<lne id="415" begin="3" end="3"/>
			<lne id="416" begin="5" end="5"/>
			<lne id="417" begin="7" end="7"/>
			<lne id="418" begin="9" end="9"/>
			<lne id="419" begin="11" end="11"/>
			<lne id="420" begin="13" end="13"/>
			<lne id="421" begin="15" end="15"/>
			<lne id="422" begin="17" end="17"/>
			<lne id="423" begin="19" end="19"/>
			<lne id="424" begin="21" end="21"/>
			<lne id="425" begin="23" end="23"/>
			<lne id="426" begin="25" end="25"/>
			<lne id="427" begin="27" end="27"/>
			<lne id="428" begin="29" end="29"/>
			<lne id="429" begin="31" end="31"/>
			<lne id="430" begin="33" end="33"/>
			<lne id="431" begin="35" end="35"/>
			<lne id="432" begin="37" end="37"/>
			<lne id="433" begin="39" end="39"/>
			<lne id="434" begin="41" end="41"/>
			<lne id="435" begin="43" end="43"/>
			<lne id="436" begin="45" end="45"/>
			<lne id="437" begin="47" end="47"/>
			<lne id="438" begin="49" end="49"/>
			<lne id="439" begin="51" end="51"/>
			<lne id="440" begin="53" end="53"/>
			<lne id="441" begin="55" end="55"/>
			<lne id="442" begin="57" end="57"/>
			<lne id="443" begin="59" end="59"/>
			<lne id="444" begin="61" end="61"/>
			<lne id="445" begin="63" end="63"/>
			<lne id="446" begin="65" end="65"/>
			<lne id="447" begin="67" end="67"/>
			<lne id="448" begin="69" end="69"/>
			<lne id="449" begin="71" end="71"/>
			<lne id="450" begin="73" end="73"/>
			<lne id="451" begin="75" end="75"/>
			<lne id="452" begin="0" end="76"/>
			<lne id="453" begin="77" end="77"/>
			<lne id="454" begin="0" end="78"/>
		</linenumbertable>
		<localvariabletable>
			<lve slot="0" name="70" begin="0" end="78"/>
		</localvariabletable>
	</operation>
</asm>
